Don't expand path argument, can cause problems
mcchrish/nnn.vim pull request #77
Opened 2020-08-26 03:08 UTC by asgeo1

Hi there, me again.

I'm still having problems with the `%:p:h` argument for `:NnnPicker`.

The `expand` call seems to be the problem. I don't think it's needed, as Vim will already expand `%:p:h` when used in a mapping anyway.  But if left in, it seems to cause problems, incorrectly expanding the path to `""` in some situations. (which then opens nnn in the root of my project, rather than the directory of the file)

This seems to fix it for me.  I tested with both neovim and vim 8, in both fish and bash.

It is a breaking change though, because you have to set the mapping without quotes around `%:p:h`. Anyone using quotes previously would have to remove them.

2020-09-04 18:35 UTC, jarun commented
@asgeo1 can you please add the note in the readme?

@maujim can you please review this change?

2020-09-07 16:55 UTC, jarun commented
> can you please add the note in the readme?

What I meant is, please mention till which version the quote was required. For example, for version x.x and below:

    example line...

2020-09-08 23:26 UTC, asgeo1 commented
Sorry for late response, I didn't notice you had commented.

The quotes were never required, even on older versions. It's just that the README previously suggested to use them, and unfortunately the quotes would now trigger an `E79: Cannot expand wildcards` error with this PR.

So I've updated the README to suggest removing quotes if they are present. Hope that is OK!

2020-09-09 01:07 UTC, jarun requested changes

2020-09-09 01:07 UTC, jarun commented on README.md
> +_NOTE there are no quotes around `%:p:h` anymore - previous versions suggested using quotes, but that can trigger a `E79: Cannot expand wildcards` error_
Please mention "v1.7 and below" specifically? _Previous_ doesn't make sense to anyone without knowledge of this issue.

2020-10-06 09:18 UTC, mcchrish commented
@asgeo1 thanks!

2020-10-06 09:18 UTC, merged